### ISSUE TITLE
face-classification-js/webcam.html is not working properly

### ISSUE THREAD

**Issue by bachkukkik** [tupleblog/face-classification-js#6]
Despite camera access being allowed, There is no graphical return on the web browser. @kittinan suspects this is due to the web browser's version.

I tested on Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) and 12.0.2 (14606.3.4). Both can't provide image return.

MacOS 10.14.2 (18C54)

![screen shot 2561-12-17 at 10 46 56](https://user-images.githubusercontent.com/9280148/50065895-739b2300-01eb-11e9-8dbe-506d0835de0f.png)

**Comment by kittinan** [comment]
Chrome 71 Remove URL.createObjectURL from MediaStream

https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems

**Comment by kittinan** [comment]
We using [tracking.js](https://github.com/eduardolundgren/tracking.js) to track face from a webcam. I think we fix this issue by we change this line in [tracking.js](https://github.com/eduardolundgren/tracking.js/blob/e725ffcf93cf3ca00b9261f0c351960962b7a27c/src/tracking.js#L62)

```javascript
element.srcObject = stream;
```
to

```javascript
try {
  element.srcObject = stream;
} catch (error) {
  element.src = URL.createObjectURL(stream);
}
```

Ref:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject#Supporting_fallback_to_the_src_property

**Comment by kittinan** [comment]
Working perfectly! direct download tracking.js from the source

**Comment by bachkukkik** [comment]
Working nicely for me too. Thanks kub @kittinan
